document.write('<script type="text/javascript" src="../three61/Detector.js"></script>');
document.write('<script type="text/javascript" src="../three61/three.min.js"></script>');
document.write('<script type="text/javascript" src="../three61/TrackballControls.js"></script>');
document.write('<script type="text/javascript" src="../util/stats.min.js"></script>');
document.write('<script type="text/javascript" src="../util/dat.gui.min.js"></script>');
document.write('<script type="text/javascript" src="../util/stats.min.js"></script>');
document.write('<script type="text/javascript" src="../util/TeapotGeometry.js"></script>');
document.write('<script type="text/javascript" src="./conte8.js"></script>');
document.write('<script type="text/javascript" src="./webgl8.js"></script>');
